import re

# Defined as a list of tuples to preserve order, which is critical for correct substitution.
# Ported from stype_imp.html JS logic.
XSAMPA_MAPPING = [
    ('ɻ', 'r\\`'),
    ('ʄ', 'j\\_<'),
    ('᷈', '_R_F'),
    ('᷄', '_H_T'),
    ('᷅', '_B_L'),
    ('ˤ', '_?\\'),
    ('ʛ', 'G\\_<'),
    ('ʀ', 'R\\'),
    ('ᵿ', 'U\\'),
    ('ʄ', 'J\\_<'),
    ('ǀ', '|\\'),
    ('ɟ', 'J\\'),
    ('ᵻ', 'I\\'),
    ('ʑ', 'z\\'),
    ('ɧ', 'x\\'),
    ('ʋ', 'v\\'),
    ('ɕ', 's\\'),
    ('ɹ', 'r\\'),
    ('ɸ', 'p\\'),
    ('ɺ', 'l\\'),
    ('ʝ', 'j\\'),
    ('ɦ', 'h\\'),
    ('ɠ', 'g_<'),
    ('ɗ', 'd_<'),
    ('ɓ', 'b_<'),
    ('ˆ', '_\\'),
    ('ħ', 'X\\'),
    ('ʘ', 'O\\'),
    ('ɴ', 'N\\'),
    ('ɰ', 'M\\'),
    ('ʟ', 'L\\'),
    ('ɮ', 'K\\'),
    ('ʜ', 'H\\'),
    ('ɢ', 'G\\'),
    ('ʙ', 'B\\'),
    ('ɘ', '@\\'),
    ('ʕ', '?\\'),
    ('ʡ', '>\\'),
    ('ǂ', '=\\'),
    ('ʢ', '<\\'),
    ('ˑ', ':\\'),
    ('ɞ', '3\\'),
    ('ɜ', 'E\\'),
    ('ǃ', '!\\'),
    ('ȵ', 'n\\'),
    ('ʐ', 'z`'),
    ('ʈ', 't`'),
    ('ʐ', 's`'),
    ('ʂ', 's`'),
    ('ɽ', 'r`'),
    ('ɳ', 'n`'),
    ('ɭ', 'l`'),
    ('ɖ', 'd`'),
    ('̃', '_~'),
    ('̚', '_}'),
    ('̽', '_x'),
    ('ʷ', '_w'),
    ('̬', '_v'),
    ('̤', '_t'),
    ('̝', '_r'),
    ('̙', '_q'),
    ('̞', '_o'),
    ('̞', '_o'),
    ('ⁿ', '_n'),
    ('̻', '_m'),
    ('ˡ', '_l'),
    ('̰', '_k'),
    ('ʲ', '_j'),
    ('ʰ', '_h'),
    ('̴', '_e'),
    ('̪', '_d'),
    ('̪', '_d'),
    ('̜', '_c'),
    ('̺', '_a'),
    ('̯', '_^'),
    ('̆', '_X'),
    ('̋', '_T'),
    ('̌', '_R'),
    ('̹', '_O'),
    ('̼', '_N'),
    ('̄', '_M'),
    ('̀', '_L'),
    ('́', '_H'),
    ('ˠ', '_G'),
    ('̂', '_F'),
    ('̏', '_B'),
    ('̘', '_A'),
    ('ʼ', '_>'),
    ('̩', '_='),
    ('̥', '_0'),
    ('̥', '_0'),
    ('ˇ', '_/'),
    ('̠', '_-'),
    ('̠', '_-'),
    ('̟', '_+'),
    ('ɨ', '1\\'),
    ('ø', '2\\'),
    ('ɾ', '4\\'),
    ('ɫ', '5\\'),
    ('ɐ', '6\\'),
    ('ɤ', '7\\'),
    ('ɵ', '8\\'),
    ('œ', '9\\'),
    ('¹', '1'),
    ('²', '2'),
    ('³', '3'),
    ('⁴', '4'),
    ('⁵', '5'),
    ('ʉ', '}'),
    ('ʒ', 'Z'),
    ('ʏ', 'Y'),
    ('χ', 'X'),
    ('ʍ', 'W'),
    ('ʌ', 'V'),
    ('ʊ', 'U'),
    ('θ', 'T'),
    ('ʃ', 'S'),
    ('ʁ', 'R'),
    ('ʀ', 'R'),
    ('ɒ', 'Q'),
    ('ɔ', 'O'),
    ('ŋ', 'N'),
    ('ɯ', 'M'),
    ('λ', 'L'),
    ('ɬ', 'K'),
    ('ɲ', 'J'),
    ('ɪ', 'I'),
    ('ɥ', 'H'),
    ('ɣ', 'G'),
    ('ɱ', 'F'),
    ('ɛ', 'E'),
    ('β', 'B'),
    ('ɑ', 'A'),
    ('ə', '@'),
    ('ʔ', '?'),
    ('̩', '='),
    ('ː', ':'),
    ('œ', '9'),
    ('ɵ', '8'),
    ('ɤ', '7'),
    ('ɐ', '6'),
    ('ˑ', '.'),
    ('ɶ', '&'),
    ('ˌ', '%'),
    ('ˈ', '"'),
    ('ð', 'D'),
    ('ç', 'C'),
    ('æ', '{'),
    ('g', 'g'),
    (' ̈', '_"'),
]

# Preallocate escaped regex patterns
ESCAPED_MAPPING = []
for ipa, xsampa in XSAMPA_MAPPING:
    # Escape special regex characters in the X-SAMPA string
    escaped_xsampa = re.escape(xsampa)
    ESCAPED_MAPPING.append((ipa, escaped_xsampa))

def xsampa_to_ipa(text: str) -> str:
    """
    Converts X-SAMPA text to IPA using the defined mapping.
    Applying substitutions sequentially to preserve precedence.
    """
    if not text:
        return text

    # Regex lookbehind for tilde
    text = re.sub(r'(?<![1-5])~', '̃', text)
    
    # Simple arrow replacement
    text = text.replace('->', '→')

    # Main mapping loop
    for ipa, patterns in ESCAPED_MAPPING:
        # Apply IPA substitutions
        text = re.sub(patterns, ipa, text)

    return text
